Id: Bandisoft.Bandizip
Publisher: Bandisoft
Name: Bandizip
Version: 7.08
License: Bandizip License Policy
InstallerType: EXE
LicenseUrl: https://www.bandisoft.com/bandizip/help/license-policy/
AppMoniker: bandizip
Tags: bandizip, 7z, zip, rar, archiver, unachiver
Description: Yet another typical ZIP archiver
Homepage: https://www.bandisoft.com/bandizip/
Installers:
  - Arch: x64
    Url: https://ux-dl.bandisoft.com/bandizip.std/BANDIZIP-SETUP-STD-ALL.EXE
    Sha256: f7a6afa38a81b87bcbeacb9f10cec456ad1901a7ef8678cf334ede25349453b4
    Switches:
        Silent: /S
        SilentWithProgress: /S

