PackageIdentifier: VideoLAN.VLC
PackageName: VLC media player
Moniker: vlc
PackageVersion: 3.0.13
Publisher: VideoLAN
Author: VideoLAN
License: (c) 2021 VideoLAN
LicenseUrl: https://www.videolan.org/legal.html
ShortDescription: VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files, and various streaming protocols.
PackageUrl: https://www.videolan.org/vlc/
Installers:
- Architecture: x64
  InstallerUrl: https://download.videolan.org/vlc/3.0.13/win64/vlc-3.0.13-win64.msi
  InstallerSha256: 1ae357a64b96dc39b08437249f7d2d9812b557d9cdc6d4c4036f3f4aa89042fb
  InstallerType: msi
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
