Id: Ytmdesktop.Ytmdesktop
Name: YouTube Music Desktop App
Version: 1.9.0
Publisher: YTMDesktop
AppMoniker: ytmd
Homepage: https://ytmdesktop.app/
Description: A unofficial player for youtube music on desktop
License: Creative Commons Zero v1.0 Universal.
LicenseUrl: https://github.com/ytmdesktop/ytmdesktop/blob/master/LICENSE.md
InstallerType: Exe
Installers:
  - Arch: x64
    Url: https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.9.0/YouTube.Music.Desktop.App.Setup.1.9.0.exe
    Sha256: ba6ad10ecaec6ed665b3584cf972e5d664af1a86f65d55069a9d2d365239a627