PackageIdentifier: Zoom.Zoom
PackageName: Zoom
Moniker: zoom
PackageVersion: 5.6.5
Publisher: Zoom Video Communications, Inc.
Author: Zoom Video Communications, Inc.
License: (c) 2021 Zoom Video Communications, Inc.
LicenseUrl: https://zoom.us/terms
ShortDescription: Enterprise video conferencing with real-time messaging and content sharing
PackageUrl: https://zoom.us/meetings
Installers:
- Architecture: neutral
  InstallerUrl: https://cdn.zoom.us/prod/5.6.5.823/ZoomInstallerFull.msi
  InstallerSha256: 15e6aeb2b775bbdc611f43bf9c631cc7b5b47a09f00bfef16a727ecef20cab85
  InstallerType: msi
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
