Id: Axosoft.GitKraken
Name: GitKraken
Version: 7.0.0
Publisher: Axosoft
Homepage: https://www.gitkraken.com/
Description: Git GUI Client.
License: Commercial (c) 2020 Axosoft, LLC.
LicenseUrl: https://www.gitkraken.com/eula
InstallerType: Exe
Installers:
  - Arch: x64
    Url: https://release.gitkraken.com/win64/GitKrakenSetup.exe
    Sha256: ccd088c266cf3ddcb045b9ec4de32477f2d8fce6c6cd639a6ed67cef6b235b04
    Switches:
      Silent: /silent
      SilentWithProgress: /silent