Id: KDE.KDEConnect
Publisher: KDE
Name: KDE Connect
Version: 1.4-247
License: GPL-2.0
LicenseUrl: https://github.com/KDE/kdeconnect-kde/blob/master/COPYING
AppMoniker: kdeconnect
Description: Enabling communication between all your devices. Made for people like you.
Homepage: https://kdeconnect.kde.org/
Installers:
  - Arch: x64
    InstallerType: appx
    Url: https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/247/artifact/kdeconnect-kde-1.4-247-windows-msvc2019_64-cl-sideload.appx
    Sha256: fdfd8bfbcb18ab5e5b470bdcf4f5c89fe3fb4d98ace4477c87d3b5545b77f09a
