# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: ImageMagick.ImageMagick
PackageVersion: 7.0.11-10
Installers:
- Architecture: x64
  InstallerUrl: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.0.11-10-Q16-HDRI-x64-dll.exe
  InstallerSha256: 8C19CECA4C18382673C721DF7207606EC668E0E42A318D4449DBD11DFCB126E6
  InstallerType: inno
- Architecture: x86
  InstallerUrl: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.0.11-10-Q16-HDRI-x86-dll.exe
  InstallerSha256: E225036F17BADFD43DD4685206F87E1179B311A080610F99F83FCE939FAD95F9
  InstallerType: inno
ManifestType: installer
ManifestVersion: 1.0.0

