# ================== General ==================
Id: TeamViewer.TeamViewer
Publisher: TeamViewer AG
Name: TeamViewer
Author: TeamViewer AG
Description: TeamViewer is a comprehensive, remote access, remote control and remote support solution that works with almost every desktop and mobile platform, including Windows, macOS, Android, and iOS. TeamViewer lets you remote in to computers or mobile devices located anywhere in the world and use them as though you were there.
AppMoniker: teamViewer
Tags: remote desktop, remote access, remote control, web conferencing

# ================== License ==================
Homepage: https://www.teamviewer.com/
License: Free For Private, Non-Commercial Use.
LicenseUrl: https://www.teamviewer.com/en/eula/

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020) 
Version: 15.7.6

InstallerType: Nullsoft
Installers:
  - Arch: x86
    Url: https://download.teamviewer.com/download/version_15x/TeamViewer_Setup.exe
    Sha256: 53957c17b78ffdc668ba59d0114e43cf810b9bec91daa9b64d346e07c10d3e95
    #Scope: machine             # Scope is not supported in this preview (5/24/2020)
    
# ManifestVersion: 0.1.0
