Id: NelsonNumericalSoftware.Nelson
Publisher: Nelson Numerical Software
Author: Allan CORNET
AppMoniker: nelson
Name: Nelson
Version: 0.4.4
License: Open Source license LGPLv2
LicenseUrl: https://raw.githubusercontent.com/Nelson-numerical-software/nelson/master/LICENSE
Description: Nelson is an array programming language providing a powerful open computing environment for engineering and scientific applications using modern C/C++ libraries (Boost, Eigen, …) and others state of art numerical libraries.It has sophisticated data structures (including cell, struct, linear systems, …), an interpreter and a high level programming language. Nelson has been developped to be an open/modular system where an user can define these own data types and operations on these data types by using overload.
Homepage: https://nelson-numerical-software.github.io/nelson-website/
Tags: "matrix,data,interpreter,language,programming,scientific"
FileExtensions: nls, nlf, nh5, mat, hdf5
InstallerType: inno
Installers:
  - Arch: x64
    Url: https://github.com/Nelson-numerical-software/nelson/releases/download/v0.4.4/Nelson-0.4.4.2521-x86-64.exe
    Sha256: 865d8638eeaae7af105e3b4eec3428d533e5ad1359811b1d701c1258b20d1eb7
