Id: CrystalDewWorld.CrystalDiskInfo
Name: CrystalDiskInfo
Version: 8.5.2
Publisher: Crystal Dew World
Author: Crystal Dew World
License: MIT
LicenseUrl: https://crystalmark.info/en/software/crystaldiskinfo/crystaldiskinfo-license/
Homepage: https://crystalmark.info/en/software/crystaldiskinfo/
Tags: utility
Description: A HDD/SSD utility software which supports a part of USB, Intel/AMD RAID and NVMe.
InstallerType: inno
Installers: 
  - Arch: x64 
    Url: https://osdn.net/frs/redir.php?m=dotsrc&f=crystaldiskinfo%2F72889%2FCrystalDiskInfo8_5_2.exe
    Sha256: 7770EB42911D4C03B67EBF0D6858B1CB817260A542AC320BA843624A48DDCFAF
