Id: Intel.IntelDriverandSupportAssistant
Version: 20.6.22.6
Name: Intel® Driver & Support Assistant
Publisher: Intel
License: Copyright © 2019 Intel Corporation. All rights reserved.
AppMoniker: Intel Driver
Description: The Intel® Driver & Support Assistant keeps your system up-to-date by providing tailored support and hassle-free updates for most of your Intel hardware.
Homepage: https://www.intel.com/content/www/us/en/support/detect.html
Installers:
  - Arch: x86
    Url: https://downloadmirror.intel.com/28425/a08/Intel-Driver-and-Support-Assistant-Installer.exe
    Sha256: B4D7B90458511B9E898C8EAF8886017AEAE6D42226DEA6C9ADF3F53FEE3FBE54
    InstallerType: exe
    Switches:
      Silent: /silent
      SilentWithProgress: /silent
