# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.0.0.schema.json
PackageIdentifier: KDE.KDEConnect
PackageVersion: 1.4.575
PackageName: KDE Connect
Publisher: KDE
License: GNU GPLv2/GNU GPLv3
LicenseUrl: https://www.gnu.org/licenses/gpl-2.0.html
Moniker: kdeconnect
Tags:
- android
- phone
- connect
- kde
- k
ShortDescription: Enabling communication between all your devices. Made for people like you.
PackageUrl: https://kdeconnect.kde.org/
Installers:
- Architecture: x86
  InstallerUrl: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/575/artifact/kdeconnect-kde-1.4-575-windows-msvc2019_64-cl.exe
  InstallerSha256: 549EFC9C3119379C726668CECFC2171901BEF58ED158B5779E546A1DA15011DE
  InstallerType: exe
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0

