Id: KDE.Okular
Version: 20.04.1-295
Name: Okular
Publisher: KDE
License: GNU General Public License v2.0
LicenseUrl: https://invent.kde.org/graphics/okular/-/raw/master/COPYING
AppMoniker: okular
Description: "Okular is a universal document viewer developed by KDE. Okular works on multiple platforms, including but not limited to Linux, Windows, Mac OS X, *BSD, etc."
Homepage: https://okular.kde.org/
Installers:
  - Arch: x64
    Url: https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/295/artifact/okular-20.04.1-295-windows-msvc2019_64-cl-sideload.appx
    Sha256: C012CB2AB08AF02338F822F4FA22E53AEE7E938A3D6FE21283C83610541488B1
    InstallerType: appx
