# ================== General ==================
Id: Ubisoft.Uplay
Publisher: Ubisoft
Name: Uplay
Author: Ubisoft
Description: Uplay service is a system that provides rewards and achievements for our players. This system also allows for games to use online content for statistics as well as the ability to share activities with friends.
AppMoniker: uplay
Tags: games, uplay, store, purchase

# ================== License ==================
Homepage: https://uplay.ubisoft.com
License: © Ubisoft Entertainment. All Rights Reserved.
LicenseUrl: https://legal.ubi.com/LegalInfoUbisoftEMEA

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020) 
Version: 110.0.8149.0

InstallerType: Nullsoft
Installers:
  - Arch: Neutral
    Url: https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UplayInstaller.exe
    Sha256: 852248592631078e5cfd0e2ee41b17dc982bf5e4daedf28f0d9f3ac334c1946e
    #Scope: machine             # Scope is not supported in this preview (5/24/2020)
    
# ManifestVersion: 0.1.0
